# Math for Data Scientists: Matrices and Gradient Descent

Matrices are a fundamental aspect of data science models and problems, including image processing, deep learning, NLP, and PCA. You will encounter matrices *many* times in your career as a data scientist. Matrices are a fundamental tool in **linear algebra**.

Gradient Descent is an optimization procedure that, in one form or another, underlies many model-fitting algorithms. The gradient, in concept, is a generalized notion of a derivative and so belongs to **calculus** or **analysis**.

## Beginning with Plain Old Algebra

Linear algebra can be used to solve for multiple unknowns at once. Let's start with a one-variable "system" before moving on to two-, three-, or many-variable systems.

Suppose we start with a one-variable system like $2X = 10$.

How do we solve this?

Now consider a two-variable system:

$2X + 4Y = 10 \\
X + 4Y = 7$

### Solution through Substitution
We _could_ solve this system by taking the first equation, solving it for X, and then plugging the result into the second:

$2X + 4Y = 10$. <br/> Thus: $\\ 2X = 10 - 4Y \\ X = 5 - 2Y$.

Plugging in to the second equation, we have:

$5 - 2Y + 4Y = 7$. <br/> Thus: $\\ 5 + 2Y = 7 \\ 2Y = 2 \\ Y = 1$.

Plugging this back into the first equation, we have:

$2X + 4 = 10$.  <br/> Thus: $\\ 2X = 6 \\ X = 3$.

And we have our solutions:  $X = 3, Y = 1$.

But this is computationally _very slow_! There is a better way:

### Solution through Elimination

Much faster is to subtract the second equation from the first:

If $2X + 4Y = 10$ and $X + 4Y = 7$,
then $(2X - X) + (4Y - 4Y) = 10 - 7$, i.e. $X = 3$. Then I could subtract this ($X + 0Y = 3$) from $X + 4Y = 7$, yielding: $4Y = 4$, i.e. $Y = 1$.

We can represent this in matrix form using the equations as our rows. The columns will correspond to the variables:


$\begin{bmatrix}
2 & 4 & 10 \\
1 & 4 & 7
\end{bmatrix}$

$\rightarrow \begin{bmatrix}
1 & 0 & 3 \\
1 & 4 & 7
\end{bmatrix}$

$\rightarrow \begin{bmatrix}
1 & 0 & 3 \\
0 & 4 & 4
\end{bmatrix}$

$\rightarrow \begin{bmatrix}
1 & 0 & 3 \\
0 & 1 & 1
\end{bmatrix}$

This is the matrix way of saying that X = 3 and that Y = 1.

There are lots of strategies in linear algebra for "reducing" a matrix to a form where there are ones down the main diagonal and zeroes everywhere else (except the rightmost column), because such a matrix represents a list of "already solved" equations: <br/>

$\begin{bmatrix}
1 & 0 & 0 & ... & 0 & b_1 \\
0 & 1 & 0 & ... & 0 & b_2 \\
... & ... & ... & ... & ... & ... \\
... & ... & ... & ... & ... & ... \\
... & ... & ... & ... & ... & ... \\
0 & 0 & 0 & ... & 1 & b_n
\end{bmatrix}$

$\; \downarrow$

$X_1 + 0X_2 + 0X_3 + ... + 0X_n = b_1 \\
0X_1 + X_2 + 0X_3 + ... + 0X_n = b_2 \\
. \\
. \\
. \\
0X_1 + 0X_2 + ... + 0X_{n-1} + X_n = b_n$

## From Scalars to Vectors

A _scalar_ has simply a single value. Any real number can be the value of a scalar.

A _vector_ must be specified by _two_ parameters: magnitude and direction. In a Cartesian coordinate system, a vector $\vec{v}$ will generally be specified by its x- and y-components, $v_x$ and $v_y$.

In that case: <br/>
    \- The magnitude of $v$ is given by $||v|| = \sqrt{v^2_x + v^2_y}$ <br/>
    \- The direction of $v$ is given by $\theta = tan^{-1}\left(\frac{v_y}{v_x}\right)$

Video on [vectors](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

## Vector Arithmetic

### Vector Addition

Vector addition is simple: Just add the x- and the y-components together:

$(8, 14) + (7, 6) = (15, 20)$

In [1]:
# Consider the vectors (8, 14) and (7, 6). Let's try using Python
# to add them together.

vec_1 = (8, 14)
vec_2 = (7, 6)

vec_1 + vec_2 == (15, 20)

False

In [2]:
vec_1 + vec_2

(8, 14, 7, 6)

What happened?

In [ ]:
# Try typing 'vec_1.' and then pressing TAB. What options do we have here?

vec_1.

Base Python is not particularly good for non-scalar arithmetic. This is one of many places where NumPy can come in very handy!

In [7]:
# Let's try this again, but this time we'll use NumPy arrays:

import numpy as np

vec_1, vec_2 = np.array([8, 14]), np.array([7, 6])
vec_1 + vec_2

array([15, 20])

### Vector Multiplication

Is base Python any better for vector _multiplication_?

In [4]:
# What happens if we multiply 3 by the vector below?

vec_1 = (4, 14)

In [5]:
3 * vec_1

(4, 14, 4, 14, 4, 14)

In [6]:
# Try multiplying the vectors (4, 14) and (8, 6)):

vec_2 = (8, 6)

vec_1 * vec_2

TypeError: can't multiply sequence by non-int of type 'tuple'

What happened? Why did we get an error?

In fact there are multiple ways of understanding the notion of vector multiplication. All are potentially useful, but the one that we'll likely be of most use is the *dot-product*, which is defined as follows:


\begin{equation}
\begin{bmatrix}
a & b \\
\end{bmatrix}
. 
\begin{bmatrix}
c \\
d
\end{bmatrix}
=
ac + bd
\end{equation}

The dot-product is the sum of the pariwise products of the vectors' entries.

In [8]:
# Now that we've got the vectors stored as NumPy arrays, let's once again
# try typing 'vec_1.' and then pressing TAB.

vec_1.dot(vec_2)

# Now we have many options! Notice that one of these options is 'dot'.
# This is our dot-product!



140

In [ ]:
# Let's use the .dot() method to calculate the dot-product of our two vectors:

# Your code here!



## Higher Dimensions: From Vectors to Matrices

For higher dimensions we can use _matrices_ to express ourselves. Suppose we had a two-variable system:

\begin{align}
a_{1,1}x_1 + a_{1,2}x_2 = c_1 \\
a_{2,1}x_1 + a_{2,2}x_2 = c_2
\end{align}

We can write this as:

$A\vec{x} = \vec{c}$,

where now $\vec{x}$ is the _vector_ $(x_1, x_2)$ and $\vec{c}$ is the _vector_ $(c_1, c_2)$.

Similarly, $A$ is the _matrix_ of coefficients that describe our system:
\begin{equation} A = 
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\end{equation}

and

\begin{equation}
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2
\end{bmatrix} =
\begin{bmatrix}
c_1 \\
c_2
\end{bmatrix}
\end{equation}

## Different Ways to Multiply

Just as there were different notions of "multiplication" for vectors, so too there are different notions of multiplication for matrices.

### Dot-Product
Very often when people talk about multiplying matrices they'll mean the dot-product:

\begin{equation}
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\times
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2}
\end{bmatrix}
=
\begin{bmatrix}
a_{1,1}\times b_{1,1} + a_{1,2}\times b_{2,1} & a_{1,1}\times b_{1,2} + a_{1,2}\times b_{2,2} \\
a_{2,1}\times b_{1,1} + a_{2,2}\times b_{2,1} & a_{2,1}\times b_{1,2} + a_{2,2}\times b_{2,2}
\end{bmatrix}
\end{equation}

Take the entries in each *row* of the left matrix and multiply them, respectively, by the entries in each *column* of the right matrix, and then add them up. This is the product we calculated above with our two vectors!

Note that matrix dot-multiplication is NOT commutative! In general, $AB \neq BA$.

#### A note about vectors and matrices

Strictly speaking, this is true for vectors as well. Above, we multiplied the *row*-vector $(a, b)$ by the *column*-vector $(c, d)$. A row-vector is simply a matrix with only one row; a column-vector is simply a matrix with only one column. What would be the result of multiplying the column-vector $(c, d)$ on the left by the row-vector $(a, b)$ on the right?

<details><summary>
    Ans.:
        </summary>
    \begin{equation}
    \begin{bmatrix}
    c \\
    d
    \end{bmatrix}
    \times
    \begin{bmatrix}
    a & b
    \end{bmatrix}
    =
    \begin{bmatrix}
    ca & cb \\
    da & db
    \end{bmatrix}
    \end{equation}
    </details>

#### Features of the Matrix Dot-Product

Observe also that in order to be able to perform the dot product on two matrices A and B, the number of columns of A must equal the number of rows of B.

Also, the number of rows of the _product_ matrix will equal the number of rows of A, and the number of columns of the product matrix will equal the number of columns of B.

In order to solve an equation like $A\vec{x} = \vec{c}$ for $\vec{x}$, we can't very well divide $\vec{c}$ by $A$! But there is a notion of matrix _inversion_ that is relevant here, which is analogous to multiplicative inversion. If we have an equation like $2x = 10$, we can simply multiply both sides by the multiplicative inverse of the coefficient of $x$, viz. $2^{-1}$. And here the point, of course, is that $2^{-1} \times 2 = 1$.

In the higher-dimensional case, what we can do is to left-multiply both sides by the _inverse matrix_ of A, denoted $A^{-1}$, and here the point is that the dot-product $A^{-1}A = I$, where $I$ is the identity matrix containing 1's along the main diagonal (upper-left to lower-right) and 0's everywhere else.

Using NumPy arrays, dot-multiply the matrices
\begin{bmatrix}
3 & 2 \\
5 & 7
\end{bmatrix}

and

\begin{bmatrix}
2 & 4 \\
3 & 10
\end{bmatrix}

in the code-cell below. Remember that you need square brackets around the whole array!

In [11]:
# Your code here!
np.matrix([[3,2],[5,7]]).dot(np.matrix([[2,4],[3,10]]))

matrix([[12, 32],
        [31, 90]])

## Tensors

Sometimes you will encounter _tensors_ in your work. A tensor is to a matrix as a matrix is to a vector. A vector has one representational dimension and a matrix has two. If you need an object with three or more representational dimensions, you're talking about a tensor. A tensor has rows (that run from left to right), columns (that run from top to bottom), and _tubes_ (that run from front to back).

## Typical Data Science Problems

Consider a typical dataset and the associated multiple linear regression problem. We have many observations (rows), each of which consists of a set of values both for the predictors (columns, i.e. the independent variables) and for the target (the dependent variable).

We can think of the values of the independent variables as our matrix $A$ of coefficients and of the values of the dependent variable as our output vector $\vec{c}$.

The task here is, in effect, to solve for $\vec{\beta}$, where we have that $A\vec{\beta} = \vec{c}$, except in general we'll have more rows than columns. This is why we won't in general be computing matrix inverses. (They're computationally expensive, anyway.) This is also why we have a problem requiring not a direct solution but rather an optimization--in our case, a best-fit line.

Using $z$ for our independent variables and $y$ for our dependent variable, we have:


\begin{equation}
\beta_1\begin{bmatrix}
z_{1,1} \\
. \\
. \\
. \\
z_{m,1}
\end{bmatrix} +
... + \beta_n\begin{bmatrix}
z_{1,n} \\
. \\
. \\
. \\
z_{m,n}
\end{bmatrix} = \begin{bmatrix}
y_1 \\
.  \\
.  \\
.  \\
y_m
\end{bmatrix}
\end{equation}

## Using NumPy to Solve a System of Linear Equations

NumPy's ```linalg``` module has a ```.solve()``` method that you can use to solve a system of linear equations!

In particular, it will solve for the vector $\vec{x}$ in the equation $A\vec{x} = b$. You should know that, "under the hood", the ```.solve()``` method does NOT compute the inverse matrix $A^{-1}$. Check out [this discussion](https://stackoverflow.com/questions/31256252/why-does-numpy-linalg-solve-offer-more-precise-matrix-inversions-than-numpy-li) on stackoverflow for a helpful discussion.

And check out the documentation for ```.solve()``` [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html).

In [12]:
# Let's use the .solve() method to solve this system of equations

X = np.array([[2, -1, 4, 6, 3], [4, 7, 1, 1, 12],
             [9, 14, 2, 2, 6], [1, 1, 1, 2, 17],
             [-3, -2, -6, 12, -5]])

y = np.array([3, 15, 20, 2, -6])

In [13]:
np.linalg.solve(X, y)

array([-14.51240389,   9.46394893,   8.31031481,   1.49992746,
        -0.2506891 ])

In [14]:
X.dot(np.linalg.solve(X, y))

array([ 3., 15., 20.,  2., -6.])

## Linear Algebra Solves the Best-Fit Line Problem

If we have a matrix of predictors $X$ and a target column $y$, we can express $\hat{y}$, the best-fit line, as  follows: (t=transpose = take inverse rows of x)

$\large\hat{y} = (X^TX)^{-1}X^Ty$.

$(X^TX)^{-1}X^T$ is sometimes called the *pseudo-inverse* of $X$. We'll have more to say about this in a future lesson when we talk about the singular value decomposition.

Let's see this in action:

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
preds = np.array(list(zip(np.random.normal(size=10), np.array(np.random.normal(size=10, loc=2)))))
target = np.array(np.random.exponential(size=10))

In [17]:
np.linalg.inv(preds.T.dot(preds)).dot(preds.T).dot(target)

array([0.04435079, 0.72348914])

In [18]:
LinearRegression(fit_intercept=False).fit(preds, target).coef_

array([0.04435079, 0.72348914])

## Calculus

But sometimes this computation is too expensive. And for other sorts of loss functions, it may not be available at all. So we turn to numerical methods, and, in particular, to the method of gradient descent. In order to gain a good grasp of this method, we'll have to review a couple items from calculus, namely:

- the Chain Rule; and
- partial differentiation.

### The Chain Rule

$\large\frac{d}{dx}[f(g(x))] = f'(g(x))g'(x)$

That is: The derivative of a *composition* of functions is: the derivative of the first applied to the second, multiplied by the derivative of the second.

So if we know e.g. that $\frac{d}{dx}[e^x] = e^x$ and $\frac{d}{dx}[x^2] = 2x$, then we can use the Chain Rule to calculate $\frac{d}{dx}[e^{x^2}]$. We set $f(x) = e^x$ and $g(x) = x^2$, so the derivative must be:

$\large\frac{d}{dx}[e^{x^2}] = (e^{x^2})(2x) = 2xe^{x^2}$.

### Partial Differentiation

Partial differentiation is required for functions of multiple variables. If e.g. I have some function $h = h(a, b)$, then I can consider how $h$ changes with respect to $a$ (while keeping $b$ constant)––that's $\frac{\partial h}{\partial a}$, and I can consider how $h$ changes with respect to $b$ (while keeping $a$ constant)––that's $\frac{\partial h}{\partial b}$. And so the rule is simple enough: If I'm differentiating my function with respect to some variable, I'll **treat all other variables as constants**.

So e.g. if 

Suppose our loss function looks like this:

$\large\xi(x, y, z) = x^2y^5z^3 - ze^{cos(xy)} + (yz)^3$;

for some parameters $x$, $y$, and $z$.

What are the partial derivatives of this function?

$\large\frac{\partial\xi}{\partial x} = ?$

<br/>
<details>
    <summary>
        Check
    </summary>
    <br/>
    $2xy^5z^3 + yze^{cos(xy)}sin(xy)$
    </details>
<br/>

$\large\frac{\partial\xi}{\partial y} = ?$

<br/>
<details>
    <summary>
        Check
    </summary>
    <br/>
    $5x^2y^4z^3 + xze^{cos(xy)}sin(xy) + 3y^2z^3$
    </details>
<br/>

$\large\frac{\partial\xi}{\partial z} = ?$

<br/>
<details>
    <summary>
        Check
    </summary>
    <br/>
    $3x^2y^5z^2 - e^{cos(xy)} + 3y^3z^2$
    </details>

## Gradient Descent

Suppose that we have these data points:

(1, 2), (3, 9), (5, 10),

and that we're interested in constructing a best-fit line through them.

Now this optimization problem has a well-known solution and we could simply plug in our values here into that formula.

The solution to a linear regression problem is a matter of minimizing the sum of squared distances between actual y-values and the line's predictions.

More generally, model optimization involves setting the derivative of the function you want to minimize (for a linear regression, this would be the sum of the squared distances between $y$ and $\hat{y}$) to zero, and then solving for the parameters that define the model (for a linear regression, this would be the slope and y-intercept).

But this is not always easily or efficiently done. Sometimes the loss function is quite complicated and it is not a straightforward matter to set the derivative equal to zero and to solve the resulting equation(s) for the missing parameters.

Sometimes it's easier or more efficient to:

### Gradient Descent in Words
- make a guess at where the function attains its minimum value; and then
- calculate the derivative at that point; and then
- use that value to decide how to make your next guess!

Repeat until we get the derivative as close as we like to 0.

This procedure (in particular, the last step) is possible because of how the gradient is defined.

The gradient is a kind of higher-order derivative for multi-variable functions. In particular, it is a vector defined as follows:

$\large\nabla f(x_1, ... , x_n) = \frac{\partial f}{\partial x_1}\hat{x_1} + ... + \frac{\partial f}{\partial x_n}\hat{x_n}$

where $\hat{x_k}$ is the unit vector in the $\vec{x_k}$-direction.
 
Recall that, in the single-variable case, a positive derivative indicates an increasing function and a negative derivative indicates a decreasing function.

In the multivariate case, the gradient tells us how the function is changing **in each dimension**. And that means that **the gradient will point in the direction of steepest increase**.

Let's look back at our [3-d plotter](https://academo.org/demos/3d-surface-plotter/).

Therefore, if we want to improve our guess at the minimum of our loss function, we'll move in the **opposite direction** of the gradient away from our last guess. Hence we are using the *gradient* of our loss function to *descend* to the minimum value of that loss function.

### Example

Let's try this with our three data points above.

You may recall that the parameters that produce the best-fit line for the three points above are:

$\beta_0 = 1$; <br/>
$\beta_1 = 2$.

But suppose we try to arrive at these values by guessing and checking, i.e. by the method of gradient descent.

Let's start with a guess of:

$\beta_0 = 3$; <br/>
$\beta_1 = 3$.

In [19]:
beta_0 = 3
beta_1 = 3

Now the function we're trying to minimize is:

$\large f(\beta_0, \beta_1) = \Sigma(y - \beta_1x - \beta_0)^2$.

So we have:

$\large\frac{\partial f}{\partial\beta_0} = -2\Sigma(y - \beta_1x - \beta_0)$; and

$\large\frac{\partial f}{\partial\beta_1} = -2\Sigma x(y - \beta_1x - \beta_0)$.

Note that if we plug in $\beta_0$ = 1, $\beta_1$ = 2, we get 0 for these derivatives:

In [20]:
def dfdbeta0(beta_0, beta_1):
    return -2 * ((2 - beta_1*1 - beta_0) + (9 - beta_1*3 - beta_0) + (10 - beta_1*5 - beta_0))

def dfdbeta1(beta_0, beta_1):
    return -2 * ((1 * (2 - beta_1*1 - beta_0)) + (3 * (9 - beta_1*3 - beta_0)) + (5 * (10 - beta_1*5 - beta_0)))

In [21]:
partial_0 = dfdbeta0(1, 2)
partial_1 = dfdbeta1(1, 2)

In [22]:
partial_0, partial_1

(0, 0)

Let's plug in our guesses and see what happens:

In [23]:
partial_0 = dfdbeta0(3, 3)
partial_1 = dfdbeta1(3, 3)

partial_0, partial_1

(30, 106)

Since $\frac{\partial f}{\partial\beta_0}$ and $\frac{\partial f}{\partial\beta_1}$ are positive, this tells us that we need to make our guesses **smaller** for each. So we might try $\beta_0 = \beta_1 = 1$:

In [24]:
partial_0 = dfdbeta0(1, 1)
partial_1 = dfdbeta1(1, 1)

partial_0, partial_1

(-18, -70)

Now we need to make our guesses **larger**! Note that, even though $\beta_0 = 1$ is part of the optimal solution, there is no guarantee that the associated partial derivative will be 0 for all the points in parameter space where $\beta_0 = 1$, since the derivative is a function both of $\beta_0$ and of $\beta_1$.

## Step Size and Learning Rate

Suppose we make a poor estimate of our function's minimum. If we take only small steps away from our initial guess, it will take a very long time to reach the optimal value. In this situation it would be helpful to take large steps.

Now suppose that our initial guess of the minimum is quite good. If we take large steps away from this point, we may make progressively worse estimates of our optimal value! In this sitation it would be helpful to take small steps.

[Here](https://stackoverflow.com/questions/42332058/gradient-descent-thetas-not-converging) is a helpful illustration of the problem.

How can we guarantee that we don't **too large** or **too small** of a step when making a new estimate of the optimal parameter values?

Here's an elegant solution: Make the size of your step proportional to the value of the derivative at the point where you currently are in parameter space! If we're very far from the minimum, then our values will be large, and so we therefore can safely take a large step; if we're close to the minimum, then our values will be small, and so we should therefore take a smaller step.

In practice the size of the step is also a function of a hyperparameter called the "learning rate", which is a constant that gets multiplied by the value of the gradient.

## Formula

The general algorithm looks like this:

We'll make a guess, $\vec{s}$, at where our loss function attains a minimum. If we're not happy with how close the value of the gradient there is to 0, then we'll make a new guess, and the new guess will be constructed as follows:

$\large\vec{s}_{new} = \vec{s}_{old} - \alpha\nabla f(\vec{s}_{old})$,

where $\alpha$ is the learning rate.

In the one-dimensional case, we'll have:

$\large x_{new} = x_{old} - \alpha\frac{d}{dx}|_{x_{old}}$.

## Exercise

Let's write a function that will utilize gradient descent for a simple one-parameter loss function.

The inputs will be:

- a function representing the derivative of our loss function;
- an initial guess;
- a learning rate;
- a level of desired precision
- a maximum number of iterations to run through before quitting

I've started the code for you below:

In [33]:
def one_d_grad_desc(deriv, guess, alpha=0.1, prec=0.000001, max_iter=10**5):
    for _ in range(max_iter):
        old_x = guess
        guess = old_x - alpha * deriv(old_x)
        
        step = guess - old_x
        if abs(guess)<prec:
            break
        return guess
        pass

### Test It!

Once you've got the function coded, try it out on some simple one-dimensional functions!

Try it on:

- `deriv` = $2x$. What answer should you get here?

- `deriv` = $10^x - 100$. What answer should you get here?

- **loss function** = $3x^3 - 3x^2 + x - 2$

- **loss function** = $(4x + 5)^2$

In [35]:
one_d_grad_desc(deriv=lambda x: 2*x, guess=2, alpha=0.1, prec=0.000001, max_iter=10**5)

1.6